language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t roshan312/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roshan312/docker-react npm run test -- --coverage